Auto registering log channel
LaraBug/LaraBug pull request #58
Opened 2021-05-13 15:41 UTC by HajMo

This pull request will enable LaraBug without registering it manually as it's described in installation guide in project details page.

2021-05-14 06:59 UTC, Cannonb4ll commented
What if users want to disable it?

2021-05-14 07:49 UTC, HajMo commented
They can delete the `login_key` value in `.env` or we can add a new env variable to decide if the service is enabled.

2021-05-14 10:19 UTC, SebastiaanKloos commented
@HajMo There should be an easy option to disable this feature as the October CMS plugin would break when merging this PR. Configuring config files is very personal and that's possibly why this does not exist in the package. @Cannonb4ll what do you think?

2021-05-14 10:21 UTC, Cannonb4ll commented
Yes I agree, I'm not too sure about this PR, of course, it is nice, but I recon it'll do more harm rather than it being helpful.

2021-05-14 10:56 UTC, HajMo commented
@SebastiaanKloos We can add more checks in the [condition](https://github.com/LaraBug/LaraBug/blob/e84470f5f9e0ee6bcb02c9747fe010c4b3c102c4/src/ServiceProvider.php#L72) with config option that decide if this feature is enabled, something like:
```php
if (config('larabug.login_key') && config('larabug.auto_register')) {
    // Register
}
```
And in `config/larabug.php` there's will be boolean `auto_register` variable. I think this will be a solution.

2021-05-19 07:09 UTC, Cannonb4ll commented
I'm still quite unsure whether to merge this at this point.

2021-05-21 18:13 UTC, HajMo commented
@SebastiaanKloos What you think?

2021-05-26 17:14 UTC, SebastiaanKloos commented
> @SebastiaanKloos What you think?

As @Cannonb4ll already said, we are still unsure whether we are going to merge this.

Let's leave this PR open for now and see if more users want this merged.

2021-06-01 09:55 UTC, lloricode commented on composer.json
> +    "name": "hajmo/larabug",
is this intended?

2021-06-01 09:56 UTC, lloricode requested changes
please update to `larabug/larabug`

2021-06-01 10:01 UTC, lloricode commented
> Yes I agree, I'm not too sure about this PR, of course, it is nice, but I recon it'll do more harm rather than it being helpful.

You have point, let developer manage since, so developer will aware of configuration rather than register automagically

2021-06-01 17:42 UTC, closed without merging

2021-06-01 17:45 UTC, SebastiaanKloos commented
@HajMo I appreciate the work you've put in the PR. However, we are not going to implement this in the near future. 

I recommend forking the repo and adding your functionality, or creating your own package requiring the larabug/larabug package. Which automatically sets the logging configuration. 

@Cannonb4ll @Glennmen do you agree?

2021-06-02 08:13 UTC, Cannonb4ll commented
Yes, for now I agree. Once this gets more replies, comments and genuine use-case examples I'd be glad to take another look at it.